Alarm melody
VladimirBrejcha/Rise pull request #12
Opened 2023-07-09 13:55 UTC by VPOneDev

completed PlayAlarmMelody

2023-07-10 03:00 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/AlarmMelody/PlayAlarmMelody.swift
> +    private func smoothSound() {
Название не отражает, что делает метод
smooth sound я перевёл как плавный звук
звучит, как будто это некий объект — звук

На самом деле метод повышает `.volume` у плеера

Предлагаю ренейминг в `increaseVolume` (увеличить громкость)

Про нейминги рекомендую почитать https://www.swift.org/documentation/api-design-guidelines/#naming
если не читал :)

2023-07-10 03:04 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/AlarmMelody/PlayAlarmMelody.swift
> +    private func smoothSound() {
Название не отражает, что делает метод
smooth sound я перевёл как плавный звук
звучит, как будто это некий объект — звук

На самом деле метод повышает .volume у плеера

Предлагаю ренейминг в increaseVolume (увеличить громкость)

Про нейминги рекомендую почитать https://www.swift.org/documentation/api-design-guidelines/#naming
если не читал :)

2023-07-10 03:06 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/AlarmMelody/PlayAlarmMelody.swift
> +    private func seekAfterPlayinEnd() {
Тут тоже с неймингом беда, я не смог перевести что означает это словосочетание 😁
Предлагаю опять-же называть буквально, как оно есть, например `loopAudio`

Про нейминги рекомендую почитать https://www.swift.org/documentation/api-design-guidelines/#naming
если не читал :)

2023-07-10 03:12 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/AlarmMelody/PlayAlarmMelody.swift
> +                                                   .mixWithOthers])
Для чего нам нужен `.mixWithOthers`?
Я думаю в случае будильника лучше "перебивать" звуки любых других приложений

2023-07-10 03:14 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/AlarmMelody/PlayAlarmMelody.swift
> +            print("Audio session error active")
Для логов в проекте используем `log(.error, "")`

2023-07-10 03:15 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/AlarmMelody/PlayAlarmMelody.swift
> +            print("Audio session error pause")
Для логов в проекте используем `log(.error, "")`

2023-07-10 03:17 UTC, VladimirBrejcha commented
Судя по [документации](https://developer.apple.com/documentation/avfaudio/avaudiosession/category/1616509-playback) у нас сейчас не будет работать звук в бекграунде
Нужно добавить 

> audio value to the [UIBackgroundModes](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/plist/info/UIBackgroundModes) key in your information property list file.

2023-07-10 03:18 UTC, VladimirBrejcha requested changes
Оставил пару минорных комментов по неймингам и логам
Более важно — нужно посмотреть как ведёт себя в бекграунде и проверить нужен ли .mixWithOthers

2023-07-14 16:37 UTC, vpavlovdev commented on DomainLayer/Sources/DomainLayer/UseCases/AlarmMelody/PlayAlarmMelody.swift
> +                                                   .mixWithOthers])
Эти параметры нужны для работы в бэкграунде

2023-07-14 16:38 UTC, VladimirBrejcha approved these changes

2023-07-14 16:40 UTC, merged