Local notifications
VladimirBrejcha/Rise pull request #13
Opened 2023-07-10 02:12 UTC by Artem-Chzh

@VladimirBrejcha

2023-07-10 03:58 UTC, VladimirBrejcha requested changes

2023-07-10 03:58 UTC, VladimirBrejcha commented on Core/Sources/Core/NotificationManager.swift
> +                print("Notification settings: \(settings)")
Для логов в проекте используем `log(.info, "")`

2023-07-10 03:58 UTC, VladimirBrejcha commented on Core/Sources/Core/NotificationManager.swift
> +  public static func registerLocal() {
Нейминг не очень хороший
"зарегистрировать что-то локальное"
не очень понятно что регистрируем

Предлагаю назвать буквально — запросить разрешение на уведомления
Но так как мы уже в NotificationManager, можно не упоминать уведомления, это и так понятно из контекста
запросить разрешения requestPermissions

2023-07-10 03:58 UTC, VladimirBrejcha commented on Core/Sources/Core/NotificationManager.swift
> +//    let notificationCenter = UNUserNotificationCenter.current()
Неиспользуемый код нужно удалить. К нему всегда можно вернуться через историю .git

2023-07-10 03:58 UTC, VladimirBrejcha commented on Core/Sources/Core/NotificationManager.swift
> +    public static func removeNotification(){
Нейминг не очень хороший, потому что из него не видно всех сайд-эффектов вызова этой функции
А сайд-эффект здесь такой, что мы удаляем **ВСЕ** ожидающие запросы

Предлагаю именовать буквально:
отменить все ожидающие запросы
`cancelAllPendingRequests`

при этом пользователю `NotificationManager` не нужно знать о его внутренних сущностях (`request`, `pending request`)
Поэтому можно добавить абстракции, например назвать:
отменить будущие уведомления
`cancelPendingNotifications`

и учитывая что мы уже находимся в `NotificationManager` и из контекста можно сделать выводы что работаем с уведомлениями, предлагаю опустить слово notifications и оставить `cancelPending` или `resetPending`

2023-07-10 03:58 UTC, VladimirBrejcha commented on Core/Sources/Core/NotificationManager.swift
> +        notificationContent.sound = .default
Как то упустили что у нас нет собственного звука для уведомлений
Нужно будет добавить в другие задачи

2023-07-10 03:58 UTC, VladimirBrejcha commented on Core/Sources/Core/NotificationManager.swift
> +            guard granted else { return }
По сути не обрабатывается ситуация в которой пользователь отказался давать доступ
А это значит мы не сможем ему даже сообщить о том что пора вставать если приложение не запущено, то есть он пропустит будильник
Добавлю отдельную задачу на этот сценарий

2023-07-10 03:58 UTC, VladimirBrejcha commented on Core/Sources/Core/NotificationManager.swift
> +            guard granted else { return }
https://github.com/VladimirBrejcha/Rise/projects/1#card-89821630

2023-07-10 03:58 UTC, VladimirBrejcha commented on Core/Sources/Core/NotificationManager.swift
> +        notificationContent.sound = .default
https://github.com/VladimirBrejcha/Rise/projects/1#card-89821634
Займусь

2023-07-10 03:58 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +//  File.swift
В свифт пакетах не используем копирайты (они всё равно неправильно проставляют название файла)

2023-07-10 03:58 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +public protocol Notification: AnyObject {
из названия юз кейса не очень понятно что он делает
юз кейс это фича или даже простое действие, поэтому часто выгодно использовать глаголы

В нашем случае у протокола объявлен всего один метод `resheduleNotification`, я думаю можно использовать это в названии юз кейса, например:
`RescheduleNotifications` (добавил `s` так как их несколько)

Второй момент: фактически мы тут хотим работать только с уведомлениями касающимися режима, поэтому  наверное стоит добавить слово Schedule, например:
`RefreshScheduleNotifications`

2023-07-10 03:58 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +    func reScheduleNotification()
Если заменить название метода на `callAsFunction()`, то мы сможем прикольно использовать это в местах использования обращаясь напрямую через класс

Пример:

```swift
public protocol DeleteSchedule {
  func callAsFunction()
}

// используется вот так
let deleteSchedule: DeleteSchedule

deleteSchedule()
```

2023-07-10 03:58 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +    func reScheduleNotification()
Можешь посмотреть по проекту еще примеры

2023-07-10 03:58 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +        self.cancellable = scheduleRepository.publisher().sink(receiveValue: { _ in })
Тут в `receiveValue` забыл обработать `reschedule`

2023-07-10 03:58 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +        let dateArray = [timeToSleepToday, timeToSleepTommorow, Date().addingTimeInterval(5)]
Тут забыл удалить отладочный код `Date().addingTimeInterval(5)`

2023-07-10 03:58 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +        guard let timeToSleepTommorow = getSchedule.tomorrow()?.toBed else { return }
Здесь я думаю нам было бы круто устанавливать сразу на неделю вперед например. или даже на 10 дней
Сейчас сделаю метод в `getSchedule` для доступа к дням

2023-07-10 03:58 UTC, VladimirBrejcha commented on Rise/AppDelegate.swift
> +            useCaseLocator.notification.reScheduleNotification()
Зачем рескедулить на уходе в бекграунд? 🤔

2023-07-10 03:58 UTC, VladimirBrejcha commented on Rise/AppDelegate.swift
> +            UNUserNotificationCenter.current().delegate = self
Делегат уже устанавливается в `didFinishLaunchingWithOptions`

2023-07-11 02:46 UTC, Artem-Chzh commented on Core/Sources/Core/NotificationManager.swift
> +  public static func registerLocal() {
Переименовал
<img width="621" alt="Снимок экрана 2023-07-11 в 11 45 47" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/b4f47856-06c3-4479-8aa4-88aed133bf14">

2023-07-11 02:48 UTC, Artem-Chzh commented on Core/Sources/Core/NotificationManager.swift
> +//    let notificationCenter = UNUserNotificationCenter.current()
Удалил
<img width="591" alt="Снимок экрана 2023-07-11 в 11 47 44" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/8349d401-e042-453c-882c-92debb173556">

2023-07-11 02:54 UTC, Artem-Chzh commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +        let dateArray = [timeToSleepToday, timeToSleepTommorow, Date().addingTimeInterval(5)]
Удалил
<img width="587" alt="Снимок экрана 2023-07-11 в 11 53 42" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/a34d5b93-feec-4eb5-aa64-93820e96a262">

2023-07-11 03:12 UTC, Artem-Chzh commented on Rise/AppDelegate.swift
> +            useCaseLocator.notification.reScheduleNotification()
Если его тут не вызывать, то после закрытия и/или свертывания приложения не будут перепланированы уведомления

2023-07-11 03:15 UTC, Artem-Chzh commented on Rise/AppDelegate.swift
> +            UNUserNotificationCenter.current().delegate = self
убрал
<img width="587" alt="Снимок экрана 2023-07-11 в 12 14 16" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/2ec86ed2-f004-4a3f-add9-711cd508186d">

2023-07-11 03:22 UTC, Artem-Chzh commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +//  File.swift
Удалил в Notification и NotifyToSleep. Не знал, да и не обращал внимание когда создавал файл.
<img width="587" alt="Снимок экрана 2023-07-11 в 12 20 48" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/87031f67-7954-48ac-bfeb-2c1372021d1e">
<img width="587" alt="Снимок экрана 2023-07-11 в 12 20 43" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/e9d755be-c0da-439c-8066-c38fb4016259">

2023-07-11 03:41 UTC, Artem-Chzh commented on Core/Sources/Core/NotificationManager.swift
> +    public static func removeNotification(){
Переименовал
<img width="627" alt="Снимок экрана 2023-07-11 в 12 38 51" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/28fd269d-e192-4125-ad28-2f1fecc59892">

2023-07-11 03:42 UTC, Artem-Chzh commented on Core/Sources/Core/NotificationManager.swift
> +        notificationContent.sound = .default
Получается пока тут ничего не меняю

2023-07-11 03:45 UTC, Nouble-Bushido commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +public protocol Notification: AnyObject {
Поменял
<img width="627" alt="Снимок экрана 2023-07-11 в 12 44 52" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/68eed47d-7649-4171-b7e6-c53070946062">

2023-07-11 03:52 UTC, Artem-Chzh commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +    func reScheduleNotification()
Переименовал
<img width="623" alt="Снимок экрана 2023-07-11 в 12 51 51" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/839f6c81-914e-4dfc-a635-f2acd8fa363e">

2023-07-11 05:07 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +        let dateArray = [timeToSleepToday, timeToSleepTommorow, Date().addingTimeInterval(5)]
Ага, тут ещё опечатка Tommorow -> Tomorrow

2023-07-11 05:10 UTC, VladimirBrejcha commented on Rise/AppDelegate.swift
> +            useCaseLocator.notification.reScheduleNotification()
А зачем перепланировать после закрытия и/или сворачивания?

Я думаю хватит двух триггеров для перепланировки:
1. Когда запускаем приложение, на случай если запланированные n уведомлений уже закончились (например юзер несколько дней не запускал приложение)
2. Когда меняется/удаляется/создается Schedule, потому что в этом случае могли измениться даты отхода ко сну (или вообще их больше может не быть если режим удалили)

2023-07-11 06:03 UTC, Artem-Chzh commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +        guard let timeToSleepTommorow = getSchedule.tomorrow()?.toBed else { return }
Сделал на 10 дней
<img width="1052" alt="Снимок экрана 2023-07-11 в 14 58 06" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/df08ee2d-da61-4858-b310-d67a1326c680">

2023-07-11 07:15 UTC, Artem-Chzh commented on Core/Sources/Core/NotificationManager.swift
> +                print("Notification settings: \(settings)")
Сделал
<img width="1052" alt="Снимок экрана 2023-07-11 в 16 14 47" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/f1040f95-4731-4a71-a01d-a64d4ff6eaed">

2023-07-11 07:16 UTC, Artem-Chzh commented on Core/Sources/Core/NotificationManager.swift
> +            guard granted else { return }
ок

2023-07-11 07:18 UTC, Artem-Chzh commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +        let dateArray = [timeToSleepToday, timeToSleepTommorow, Date().addingTimeInterval(5)]
теперь вообще этого нет)

2023-07-11 07:19 UTC, Nouble-Bushido commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +    func reScheduleNotification()
Но если потом искать где это использовалась не совсем удобно по поиску

2023-07-11 07:25 UTC, Artem-Chzh commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +        self.cancellable = scheduleRepository.publisher().sink(receiveValue: { _ in })
Сделал как по инструкции, и reschedule нет у меня в этом классе.
<img width="493" alt="Снимок экрана 2023-07-11 в 16 22 44" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/dde62b3c-8b5b-4d73-a577-e4579c7643c9">
<img width="912" alt="Снимок экрана 2023-07-11 в 16 24 52" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/e647c535-64b5-46d6-bce4-e013e13793a0">

2023-07-11 07:37 UTC, Artem-Chzh commented on Rise/AppDelegate.swift
> +            useCaseLocator.notification.reScheduleNotification()
А как она(функция) заработает если ее нигде не вызвать?

2023-07-11 08:48 UTC, VladimirBrejcha commented on Rise/AppDelegate.swift
> +            useCaseLocator.notification.reScheduleNotification()
Её нужно вызывать в этих двух случаях.
Касаемо второго случая — использовать `scheduleRepository.publisher()`, это подписка которая вызывает кложур каждый раз когда происходят изменения в базе данных по `Schedule`

2023-07-11 08:52 UTC, VladimirBrejcha commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +        self.cancellable = scheduleRepository.publisher().sink(receiveValue: { _ in })
> Сделал как по инструкции

В инструкции пустой кложур `receiveValue: { _ in }`, он вызывается каждый раз когда меняется `Schedule` в базе данных. В этом кложуре нужно вызывать свою логику (reschedule)

> reschedule нет у меня в этом классе

Почему нет, просто он называется `callAsFunction()`, но по сути он же делает то что нужно

2023-07-13 04:57 UTC, Artem-Chzh commented on DomainLayer/Sources/DomainLayer/UseCases/Notification.swift
> +        self.cancellable = scheduleRepository.publisher().sink(receiveValue: { _ in })
Сделал
<img width="857" alt="Снимок экрана 2023-07-13 в 13 57 20" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/8189c3f9-6568-477c-9d5b-c17e8ace7376">

2023-07-13 04:58 UTC, Artem-Chzh commented on Rise/AppDelegate.swift
> +            useCaseLocator.notification.reScheduleNotification()
Получается если правильно понял, то в данном случае тоже оставляю.

2023-07-13 08:12 UTC, Artem-Chzh commented on Rise/AppDelegate.swift
> +            useCaseLocator.notification.reScheduleNotification()
В 1 случае получается здесь
<img width="852" alt="Снимок экрана 2023-07-13 в 17 11 51" src="https://github.com/VladimirBrejcha/Rise/assets/117162015/880b7572-cc50-42f0-9624-4bed5509b6e2">

2023-07-15 05:12 UTC, VladimirBrejcha commented on Rise/AppDelegate.swift
> +            useCaseLocator.notification.reScheduleNotification()
Думаю да

2023-07-15 05:13 UTC, VladimirBrejcha approved these changes

2023-07-20 06:45 UTC, merged